### PR TITLE
BACKLOG-3428 -- Creating an annotation/Dim group with a long name nee…

### PR DESCRIPTION
**Pull request by kolinus**
…ds a

different message

What was done:
1) added special case for handling long names

### CODE REVIEW

**Comment by kolinus** [comment]
@pminutillo  @kurtwalker  could you please review

**Comment by bytekast** [comment]
is this just an issue with the XmlMetaStore? and not the RepoMetaStore?

**Comment by kurtwalker** [comment]
Please localize the error message

**Comment by kolinus** [comment]
@bytekast the issue appeared in XmlMetaStoreElement -- faulty fileimputstream is created there
@kurtwalker none of the messages is localized in XmlMetaStoreElement -- so we need a separate case for that. Don't want to mix multiple fixes in one commit.

**Comment by bytekast** [comment]
@kolinus just thinking there might be issues when switching from local to DI repo metastore (and vice versa)

**Comment by kurtwalker** [comment]
ok, I can buy a new case to localize since it looks like there is no localization in the entire metastore project

**Comment by kolinus** [comment]
[4:44:42 PM] Rowell Belen: just test to see the same issue doesn't exist there
[4:44:55 PM] Kanstantsin A Karneliuk: me too

so no issue with repository

**Pull request merged**
