### PR TITLE
[TEST] increase metastore tests coverage

### PR DESCRIPTION
**Pull request by scottyaslan**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Changed files:
==============
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreDependenciesExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementExistExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementTypeExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/security/MetaStoreElementOwnerTypeTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreElementTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithAutomaticCacheTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithPersistentCacheTest.java
  test-src/org/pentaho/metastore/test/MetaStoreFactoryTest.java
  test-src/org/pentaho/metastore/test/MultiLevelListTest.java
  test-src/org/pentaho/metastore/test/PojoChildTest.java
  test-src/org/pentaho/metastore/test/XmlMetaStoreTest.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Cube.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Dimension.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionAttribute.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionType.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Kpi.java
  test-src/org/pentaho/metastore/test/testclasses/factory/A.java
  test-src/org/pentaho/metastore/test/testclasses/factory/B.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/X.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/Y.java
  test-src/org/pentaho/metastore/test/testclasses/my/ChildElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level1Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level2Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level3Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level4Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElementAttr.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyFilenameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyMigrationElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyNameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyOtherElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/ParentElement.java
  test-src/org/pentaho/metastore/util/FileUtilTest.java

Checkstyle violations:
----------------------
Errors:File test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithAutomaticCacheTest.java
1. Message: Line has trailing spaces. at Line: 23 Column: None
2. Message: Line has trailing spaces. at Line: 28 Column: NoneFile test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithPersistentCacheTest.java
1. Message: Line has trailing spaces. at Line: 23 Column: None
2. Message: Line has trailing spaces. at Line: 28 Column: None




Unit test coverage change:
============
org.pentaho.metastore.api.exceptions.MetaStoreElementTypeExistsException:
 * instructionPercentCoverageChange : +80.00%
 * linePercentCoverageChange : +80.00%
 * complexityPercentCoverageChange : +83.33%
 * methodPercentCoverageChange : +83.33%
    
org.pentaho.metastore.api.exceptions.MetaStoreDependenciesExistsException:
 * instructionPercentCoverageChange : +67.74%
 * linePercentCoverageChange : +69.23%
 * complexityPercentCoverageChange : +60.00%
 * methodPercentCoverageChange : +60.00%
    
org.pentaho.metastore.api.exceptions.MetaStoreException:
 * instructionPercentCoverageChange : +43.75%
 * linePercentCoverageChange : +50.00%
 * complexityPercentCoverageChange : +50.00%
 * methodPercentCoverageChange : +50.00%
    
org.pentaho.metastore.util.FileUtil:
 * instructionPercentCoverageChange : +3.28%
 * branchPercentCoverageChange : +8.33%
 * linePercentCoverageChange : +6.25%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metastore.api.exceptions.MetaStoreElementExistException:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.metastore.api.security.MetaStoreElementOwnerType:
 * instructionPercentCoverageChange : +3.45%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +20.00%
 * complexityPercentCoverageChange : +14.29%

**Comment by lucboudreau** [comment]
Some checkstyle issues detected. Otherwise lookin good.

**Comment by lucboudreau** [comment]
Changed files:
==============
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreDependenciesExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementExistExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementTypeExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/security/MetaStoreElementOwnerTypeTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreElementTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithAutomaticCacheTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithPersistentCacheTest.java
  test-src/org/pentaho/metastore/test/MetaStoreFactoryTest.java
  test-src/org/pentaho/metastore/test/MultiLevelListTest.java
  test-src/org/pentaho/metastore/test/PojoChildTest.java
  test-src/org/pentaho/metastore/test/XmlMetaStoreTest.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Cube.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Dimension.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionAttribute.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionType.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Kpi.java
  test-src/org/pentaho/metastore/test/testclasses/factory/A.java
  test-src/org/pentaho/metastore/test/testclasses/factory/B.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/X.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/Y.java
  test-src/org/pentaho/metastore/test/testclasses/my/ChildElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level1Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level2Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level3Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level4Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElementAttr.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyFilenameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyMigrationElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyNameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyOtherElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/ParentElement.java
  test-src/org/pentaho/metastore/util/FileUtilTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.metastore.api.exceptions.MetaStoreElementTypeExistsException:
 * instructionPercentCoverageChange : +80.00%
 * linePercentCoverageChange : +80.00%
 * complexityPercentCoverageChange : +83.33%
 * methodPercentCoverageChange : +83.33%
    
org.pentaho.metastore.api.exceptions.MetaStoreDependenciesExistsException:
 * instructionPercentCoverageChange : +67.74%
 * linePercentCoverageChange : +69.23%
 * complexityPercentCoverageChange : +60.00%
 * methodPercentCoverageChange : +60.00%
    
org.pentaho.metastore.api.exceptions.MetaStoreException:
 * instructionPercentCoverageChange : +43.75%
 * linePercentCoverageChange : +50.00%
 * complexityPercentCoverageChange : +50.00%
 * methodPercentCoverageChange : +50.00%
    
org.pentaho.metastore.util.FileUtil:
 * instructionPercentCoverageChange : +3.28%
 * branchPercentCoverageChange : +8.33%
 * linePercentCoverageChange : +6.25%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metastore.api.exceptions.MetaStoreElementExistException:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.metastore.api.security.MetaStoreElementOwnerType:
 * instructionPercentCoverageChange : +3.45%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +20.00%
 * complexityPercentCoverageChange : +14.29%

**Comment by brosander** [comment]
Changed files:
==============
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreDependenciesExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementExistExceptionTest.java
  test-src/org/pentaho/metastore/api/exceptions/MetaStoreElementTypeExistsExceptionTest.java
  test-src/org/pentaho/metastore/api/security/MetaStoreElementOwnerTypeTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreElementTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithAutomaticCacheTest.java
  test-src/org/pentaho/metastore/stores/xml/XmlMetaStoreWithPersistentCacheTest.java
  test-src/org/pentaho/metastore/test/MetaStoreFactoryTest.java
  test-src/org/pentaho/metastore/test/MultiLevelListTest.java
  test-src/org/pentaho/metastore/test/PojoChildTest.java
  test-src/org/pentaho/metastore/test/XmlMetaStoreTest.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Cube.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Dimension.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionAttribute.java
  test-src/org/pentaho/metastore/test/testclasses/cube/DimensionType.java
  test-src/org/pentaho/metastore/test/testclasses/cube/Kpi.java
  test-src/org/pentaho/metastore/test/testclasses/factory/A.java
  test-src/org/pentaho/metastore/test/testclasses/factory/B.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/X.java
  test-src/org/pentaho/metastore/test/testclasses/factory_shared/Y.java
  test-src/org/pentaho/metastore/test/testclasses/my/ChildElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level1Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level2Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level3Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/Level4Element.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyElementAttr.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyFilenameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyMigrationElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyNameElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/MyOtherElement.java
  test-src/org/pentaho/metastore/test/testclasses/my/ParentElement.java
  test-src/org/pentaho/metastore/util/FileUtilTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.metastore.api.exceptions.MetaStoreElementTypeExistsException:
 * instructionPercentCoverageChange : +80.00%
 * linePercentCoverageChange : +80.00%
 * complexityPercentCoverageChange : +83.33%
 * methodPercentCoverageChange : +83.33%
    
org.pentaho.metastore.api.exceptions.MetaStoreDependenciesExistsException:
 * instructionPercentCoverageChange : +67.74%
 * linePercentCoverageChange : +69.23%
 * complexityPercentCoverageChange : +60.00%
 * methodPercentCoverageChange : +60.00%
    
org.pentaho.metastore.api.exceptions.MetaStoreException:
 * instructionPercentCoverageChange : +43.75%
 * linePercentCoverageChange : +50.00%
 * complexityPercentCoverageChange : +50.00%
 * methodPercentCoverageChange : +50.00%
    
org.pentaho.metastore.util.FileUtil:
 * instructionPercentCoverageChange : +3.28%
 * branchPercentCoverageChange : +8.33%
 * linePercentCoverageChange : +6.25%
 * complexityPercentCoverageChange : +12.50%
    
org.pentaho.metastore.api.exceptions.MetaStoreElementExistException:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.metastore.api.security.MetaStoreElementOwnerType:
 * instructionPercentCoverageChange : +3.45%
 * branchPercentCoverageChange : +25.00%
 * linePercentCoverageChange : +20.00%
 * complexityPercentCoverageChange : +14.29%

**Pull request merged**
